apiVersion: v1
kind: PersistentVolume
metadata:
    namespace: default
    name: elasticsearch
    labels:
        k8s-app: elasticsearch
spec:
    capacity:
        storage: 100Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Delete
    storageClassName: local-storage
    local:
        path: /var/opt/cognigy/elasticsearch
    nodeAffinity:
        required:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - cognigy-workstation-105